name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib[version='<2.2']
    - basemap
    - basemap-data-hires
    - flake8
    - future
    - instaseis
    - jsonschema
    - jupyter
    - mock
    - obspy
    - pandas
    - pytest
    - requests
    - seaborn
    - tornado
